### ISSUE TITLE
[cap-js/cds-dbs] collumns in cqn populated wrongly

### ISSUE THREAD

**Issue by sebbi08** [cap-js/cds-dbs#224]
### Description of erroneous behaviour 

We have a db model with multiple deep associations coming from a hana db
![image](https://github.com/cap-js/cds-dbs/assets/9070136/8e9a5fbe-c88d-4cbc-a20a-920257139a8a)

```cds
namespace someNamespace;


entity ACDOCA {
  key BELNR         : String; //Accounting number document
  key MANDT         : String; //Client
      BUKRS         : String; //Company code
      BUDAT         : DateTime; //Posting date of document
      EBELN         : String; //Purchasing document number
      NETDT         : DateTime; //Due Date
      EPELP         : String;
      LIFNR         : String; //Account number of vendor or creditor also known as Supplier Number
      AUGBL         : String; //Document number of clearing document or Invoice Status
      WSL           : Integer; //Amount in transaction currency
      RTCUR         : String; //Balance transaction currency
      AUGDT         : DateTime; //Payment date or Clearing date
      PARTNER       : String;
      ADDRNUMBER    : String; //Address Number
      PERSNUMBER    : String; //Person Number
      DATE_FROM     : DateTime; //Date
      CONSNUMBER    : Integer; //Sequence Number
      DOCID         : Integer;
      BUT000_REF        : Association to BUT000
                        on  BUT000_REF.CLIENT  = $self.MANDT
                        and BUT000_REF.PARTNER = $self.LIFNR;

}


entity BUT000 {
  key CLIENT       : String; // Client
  key PARTNER      : String; //Business Partner Number
      PARTNER_GUID : String; //Business Partner GUID
      NAME_ORG1    : String; //Name1 of Organization
      TAXTYPE      : String;
      DFKKBPTAXNUM_REF : Association to DFKKBPTAXNUM
                       on  DFKKBPTAXNUM_REF.PARTNER = $self.PARTNER
                       and DFKKBPTAXNUM_REF.CLIENT  = $self.CLIENT
                       and DFKKBPTAXNUM_REF.TAXTYPE = $self.TAXTYPE
}

entity DFKKBPTAXNUM {
  key PARTNER  : String; //Business Partner Number
  key CLIENT   : String; //Client
  key TAXTYPE  : String; //Tax Number Category
      TAXNUMXL : String; //Business Partner Tax Number or Supplier VAT ID
}

```

when we do a DB deep SELECT in our SQLite with dummy data, we get the following error

SELECT:
```JS
let query = (await SELECT(ACDOCA, (acdoca => {
				acdoca('*');
				if (acdoca.ERPTM_IV_DATA_REF) {
					acdoca.ERPTM_IV_DATA_REF("*");
				}
				if (acdoca.OPT_VIM_1HEAD_REF) {
					acdoca.OPT_VIM_1HEAD_REF("*")
				}
				if (acdoca.BKPF_REF) {
					acdoca.BKPF_REF("*")
				}
				if (acdoca.LFA1_REF) {
					acdoca.LFA1_REF("*");
				}

				if (acdoca.ADR2_REF) {
					acdoca.ADR2_REF("*")
				}
				if (acdoca.BSEG_REF) {
					acdoca.BSEG_REF("*")
				}
				if (acdoca.BUT000_REF) {
					acdoca.BUT000_REF((but000 => {
						but000("*")
						if (but000.DFKKBPTAXNUM_REF) {
							but000.DFKKBPTAXNUM_REF("*");
						}
					}));
				}
			})))
```
```
TypeError: Cannot create property 'PARTNER' on string 'h_DFKKBPTAXNUM_REF'
    at JoinCQNFromExpanded._buildNewAliasColumn (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/db/expand/expandCQNToJoin.js:1033:50)
    at JoinCQNFromExpanded._addAliasToColumn (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/db/expand/expandCQNToJoin.js:996:17)
    at JoinCQNFromExpanded._expandedToFlat (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/db/expand/expandCQNToJoin.js:541:36)
    at JoinCQNFromExpanded._addJoinAndElements (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/db/expand/expandCQNToJoin.js:791:10)
    at JoinCQNFromExpanded._expandedToFlat (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/db/expand/expandCQNToJoin.js:531:14)
    at JoinCQNFromExpanded._addJoinAndElements (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/db/expand/expandCQNToJoin.js:791:10)
    at JoinCQNFromExpanded._expandedToFlat (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/db/expand/expandCQNToJoin.js:531:14)
    at JoinCQNFromExpanded._createJoinCQNFromExpanded (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/db/expand/expandCQNToJoin.js:152:12)
    at JoinCQNFromExpanded.buildJoinQueries (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/db/expand/expandCQNToJoin.js:68:10)
    at createJoinCQNFromExpanded (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/db/expand/expandCQNToJoin.js:1710:52)
    at _processExpand (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/sqlite/execute.js:81:25)
    at executeSelectCQN (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/sqlite/execute.js:104:12)
    at SQLiteDatabase._read (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/db/query/read.js:75:10)
    at SQLiteDatabase.module.exports [as _READ] (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/db/generic/read.js:15:15)
    at next (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:36)
    at SQLiteDatabase.handle (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/lib/srv/srv-dispatch.js:83:6)
    at async SupplierServiceHandler.read (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/src/handler/supplierService/supplierServiceHandler.ts:14:17)
```

I have already debugged a bit in the code and found that in the `cqn` select the `columns` of the nested Entity contains the ref to the next one two times, once with and once without the expand.

![image](https://github.com/cap-js/cds-dbs/assets/9070136/575ca11e-91cd-4f3f-812f-e7c73c8c71b2)

When I remove the 5. Item marked the query resolves successfully. I already tried to query the deep data without the "*" only with the “expand” but that did not help.

### Detailed steps to reproduce
Use the CDS view and the query from above.

Here are some mock data:

ACDOCA
```csv
BELNR,MANDT,BUKRS,BUDAT,EBELN,LIFNR,AUGBL,WSL,RTCUR,AUGDT,EPELP,PARTNER,ADDRNUMBER,PERSNUMBER,DATE_FROM,CONSNUMBER,DOCID,NETDT
1001,1001,COMP1,2023-08-01T08:15:00Z,PO123,123456,Indexing,5000.00,USD,2023-08-15T08:15:00Z,001,123456,001,001,2023-08-01T08:00:00Z,1,1,2023-10-01T08:00:00Z
1002,1002,COMP2,2023-08-02T08:15:00Z,PO124,654321,Posted but not paid,6000.00,USD,2023-08-16T08:15:00Z,002,654321,002,002,2023-08-02T08:15:00Z,2,2,2023-10-02T08:00:00Z
1003,1003,COMP3,2023-08-03T08:15:00Z,PO125,789123,Indexing,7000.00,USD,2023-08-17T08:15:00Z,003,789123,003,003,2023-08-03T08:30:00Z,3,3,2023-10-03T08:00:00Z
1004,1004,COMP4,2023-08-04T08:15:00Z,PO126,987654,Rejected,8000.00,USD,2023-08-18T08:15:00Z,001,987654,004,001,2023-08-04T08:45:00Z,4,4,2023-10-04T08:00:00Z
1005,1005,COMP5,2023-08-05T08:15:00Z,PO127,456789,Cancelled,9000.00,USD,2023-08-19T08:15:00Z,002,456789,005,002,2023-08-05T09:00:00Z,5,5,2023-10-05T08:00:00Z
1006,1006,COMP6,2023-08-06T08:15:00Z,PO128,654123,Received,10000.00,USD,2023-08-20T08:15:00Z,003,654123,006,003,2023-08-06T09:15:00Z,6,6,2023-10-06T08:00:00Z
1007,1007,COMP7,2023-08-07T08:15:00Z,PO129,321987,In Process,11000.00,USD,2023-08-21T08:15:00Z,001,321987,007,001,2023-08-07T09:30:00Z,7,7,2023-10-07T08:00:00Z
1008,1008,COMP8,2023-08-08T08:15:00Z,PO130,789456,Blocked due to price,12000.00,USD,2023-08-22T08:15:00Z,002,789456,008,002,2023-08-08T09:45:00Z,8,8,2023-10-08T08:00:00Z
1009,1009,COMP9,2023-08-09T08:15:00Z,PO131,123789,Discrepancy,13000.00,USD,2023-08-23T08:15:00Z,003,123789,009,003,2023-08-09T10:00:00Z,9,9,2023-10-09T08:00:00Z
1010,1010,COMP10,2023-08-10T08:15:00Z,PO132,456321,Confirmed duplicate,14000.00,USD,2023-08-24T08:15:00Z,001,456321,010,001,2023-08-10T10:15:00Z,10,10,2023-10-10T08:00:00Z
```

BUT000
```csv
CLIENT,PARTNER,PARTNER_GUID,NAME_ORG1,TAXTYPE
1001,123456,GUID1,Organization1,TaxType1
1002,654321,GUID2,Organization2,TaxType2
1003,789123,GUID3,Organization3,TaxType3
1004,987654,GUID4,Organization4,TaxType4
1005,456789,GUID5,Organization5,TaxType5
1006,654123,GUID6,Organization6,TaxType6
1007,321987,GUID7,Organization7,TaxType7
1008,789456,GUID8,Organization8,TaxType8
1009,123789,GUID9,Organization9,TaxType9
1010,456321,GUID10,Organization10,TaxType10
```

DFKKBPTAXNUM
```csv
PARTNER,CLIENT,TAXTYPE,TAXNUMXL
123456,1001,TaxType1,1234567890
654321,1002,TaxType2,2345678901
789123,1003,TaxType3,3456789012
987654,1004,TaxType4,4567890123
456789,1005,TaxType5,5678901234
654123,1006,TaxType6,6789012345
321987,1007,TaxType7,7890123456
789456,1008,TaxType8,8901234567
123789,1009,TaxType9,9012345678
456321,1010,TaxType10,0123456789

```

**Comment by sebbi08** [comment]
OK as always you debug this for some hours, find no solution, create a bug ticket, debug a little more and find the solution.

So it seems that as I am using Typescript the compiler is complaining that the associations might be `undefined`
![image](https://github.com/cap-js/cds-dbs/assets/9070136/135ae57a-9a65-4d93-abbe-13774a5af34b)

preventing this by either
```JS
acdoca.ERPTM_IV_DATA?.("*");
```
or

```JS
if (acdoca.ERPTM_IV_DATA) {
    acdoca.ERPTM_IV_DATA("*");
}
```

will call the `apply` and `get` function in the projection proxy

![image](https://github.com/cap-js/cds-dbs/assets/9070136/7cb3a368-4dd0-49d7-849b-a2513908405c)

when I add @ts-ignore to the properties, the call is working like expected.

```JS
let query = (await SELECT(ACDOCA, (acdoca => {
	acdoca('*');
	//@ts-ignore
	acdoca.ERPTM_IV_DATA("*");
	//@ts-ignore
	acdoca.OPT_VIM_1HEAD("*");
	//@ts-ignore
	acdoca.BKPF("*");
	//@ts-ignore
	acdoca.LFA1("*");
	//@ts-ignore
	acdoca.ADR2("*");
	//@ts-ignore
	acdoca.BSEG("*");
	//@ts-ignore
	acdoca.BUT000((but000 => {
		but000("*");
		//@ts-ignore
		but000.DFKKBPTAXNUM("*");
	}));
})))
```

**Comment by sebbi08** [comment]
One solution is to make the properties for the select non optional
![image](https://github.com/cap-js/cds-dbs/assets/9070136/21ec4c93-2a92-46f3-aaee-2bcbfc55abe4)

**Comment by patricebender** [comment]
Hi @sebbi08,

I supsect you are not using the `cap-js` database driver, but the one which is included in the `cds` runtime. This can be seen in your stacktrace:

```
    at JoinCQNFromExpanded._buildNewAliasColumn (/home/sebastian/code/sovanta/aldi/supplier-portal-ap-ar/node_modules/@sap/cds/libx/_runtime/db/expand/expandCQNToJoin.js:1033:50)
```

If you inspect your db environment with `❯ cds env requires.db`, the output must look like this:
```
{
  impl: '@cap-js/sqlite',
  credentials: { url: ':memory:' },
  kind: 'sqlite'
}
```

Could you please check?

**Comment by sebbi08** [comment]
🙈 yea i had some `OUT OF MEMORY` errors with the new version and tested the old driver and missed to revert it :/
