### ISSUE TITLE
@cap-js/sqlite@1.1.0 breaks cds.test with mocks

### ISSUE THREAD

**Issue by pwasem** [cap-js/cds-dbs#231]
### Description of erroneous behaviour 

`@cap-js/sqlite@1.1.0` breaks [cds.test](https://cap.cloud.sap/docs/node.js/cds-test#running-a-cap-server) with mocks.

Given a project with an [imported external service](https://cap.cloud.sap/docs/guides/using-services#external-service-api)

And a test file which looks like this.

```typescript
import { cwd } from 'process'
import cds from '@sap/cds'

const cmd = 'serve'
const args = [
  '--project',
  cwd(),
  '--with-mocks'
]
const { axios, data } = cds.test(cmd, args)

describe('example test', () => {
  afterEach(async () => {
    await data.reset() 
  })

 // some tests
})
```

Calling `data.reset()` will throw an error:

```shell
'SqliteError: no such table: External_Service_Some_Table in:
DELETE FROM External_Service_Some_Table as Some_Table
    at Database.prepare (/Users/foo/Projects/some-service/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at SQLiteService.prepare (/Users/foo/Projects/some-service/node_modules/@cap-js/sqlite/lib/SQLiteService.js:47:23)
    at SQLiteService.onSIMPLE (/Users/foo/Projects/some-service/node_modules/@cap-js/db-service/lib/SQLService.js:151:25)
    at next (/Users/foo/Projects/some-service/node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:36)
    at SQLiteService.onDeep (/Users/foo/Projects/some-service/node_modules/@cap-js/db-service/lib/deep-queries.js:26:39)
    at next (/Users/foo/Projects/some-service/node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:36)
    at SQLiteService.fill_in_keys (/Users/foo/Projects/some-service/node_modules/@cap-js/db-service/lib/fill-in-keys.js:75:10)
    at next (/Users/foo/Projects/some-service/node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:36)
    at SQLiteService.handle (/Users/foo/Projects/some-service/node_modules/@sap/cds/lib/srv/srv-dispatch.js:83:6)
    at SQLiteService.dispatch (/Users/foo/Projects/some-service/node_modules/@sap/cds/lib/srv/srv-dispatch.js:45:15)
    at /Users/foo/Projects/some-service/node_modules/@sap/cds/lib/srv/srv-dispatch.js:35:15
    at Array.map (<anonymous>)
    at SQLiteService.dispatch (/Users/foo/Projects/some-service/node_modules/@sap/cds/lib/srv/srv-dispatch.js:34:59)
    at SQLiteService._begin [as dispatch] (/Users/foo/Projects/some-service/node_modules/@sap/cds/lib/srv/srv-tx.js:207:15)
    at DataUtil.delete (/Users/foo/Projects/some-service/node_modules/@sap/cds/lib/utils/data.js:18:7)
    at DataUtil.reset (/Users/foo/Projects/some-service/node_modules/@sap/cds/lib/utils/data.js:25:5)
    at Object.<anonymous> (/Users/foo/Projects/some-service/test/service.test.ts:25:7)'
```

Same works with `@cap-js/sqlite@1.0.1`

Has been tested with latest `@sap/cds@7.2.0`

The issue is only related to `@cap-js/sqlite`

### Details about your project

|:---------------------- | ----------- |
| Node.js                | v18.17.1    |
| @sap/cds               | 7.2.0       |
| @sap/cds-compiler      | 4.1.2       |
| @sap/cds-dk            | 7.2.0       |
| @sap/cds-dk (global)   | 7.2.0       |
| @sap/eslint-plugin-cds | 2.6.3       |
| @sap/cds-mtxs          | 1.10.0      |

**Comment by patricebender** [comment]
just to make sure this still is relevant. Would you upgrade to `1.2.1` and check if this resolves your issue?

**Comment by pwasem** [comment]
> just to make sure this still is relevant. Would you upgrade to `1.2.1` and check if this resolves your issue?

@patricebender no still broken in `1.2.1`.  The issue occurs as of `1.1.0`

**Comment by pwasem** [comment]
@patricebender Seems like the tables for the mocked external services are not being created at all. But still considered for deletion. Hence the error.

**Comment by patricebender** [comment]
could you provide a minimal sample + steps to reproduce?

**Comment by patricebender** [comment]
Closing due to inactivity, if you want to re-open, feel free to do so
