### ISSUE TITLE
Resource not currently part of this pool

### ISSUE THREAD

**Issue by nimbit-software** [cap-js/cds-dbs#253]
We recently migrated from the old cap/postgres library to the new official version. For the most part it works but there seems to be a problem with the connection pool. 

We tried different database providers in the hopes that it would help but we get the same error. 

### Description of erroneous behaviour 
From what i can tell it only happens after the app hasnt been used for a certain amount of time, i image that the connection pool closes some of the connections but im not totally sure. 

Once the app gets restarted it all works again. 

Here is the error message 
```
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR [cds] - Error: Client has encountered a connection error and is not queryable
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR at /home/vcap/app/node_modules/pg/lib/client.js:526:17
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR at async Object.run (/home/vcap/app/node_modules/@cap-js/postgres/lib/PostgresService.js:150:24)
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR at async Promise.all (index 0)
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR at async PostgresService.begin (/home/vcap/app/node_modules/@cap-js/db-service/lib/common/DatabaseService.js:61:7)
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR at async PostgresService._begin [as dispatch] (/home/vcap/app/node_modules/@sap/cds/lib/srv/srv-tx.js:205:3)
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR at async ApplicationService.<anonymous> (/home/vcap/app/node_modules/@sap/cds/libx/_runtime/common/generic/crud.js:67:16)
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR at async next (/home/vcap/app/node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:17)
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR at async ApplicationService.handle (/home/vcap/app/node_modules/@sap/cds/lib/srv/srv-dispatch.js:77:10)
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR at async _readCollection (/home/vcap/app/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/read.js:249:19) {
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR id: '1847353',
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR level: 'ERROR',
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR timestamp: 1695738852194
2023-09-26T14:34:12.194+0000 [APP/PROC/WEB/0] STDERR }
2023-09-26T14:34:12.195+0000 [APP/PROC/WEB/0] STDERR Error: Resource not currently part of this pool
2023-09-26T14:34:12.195+0000 [APP/PROC/WEB/0] STDERR at Pool.release (/home/vcap/app/node_modules/generic-pool/lib/Pool.js:518:9)
2023-09-26T14:34:12.195+0000 [APP/PROC/WEB/0] STDERR at Pool.release (/home/vcap/app/node_modules/@cap-js/db-service/lib/common/generic-pool.js:29:22)
2023-09-26T14:34:12.195+0000 [APP/PROC/WEB/0] STDERR at PostgresService.release (/home/vcap/app/node_modules/@cap-js/db-service/lib/common/DatabaseService.js:105:22)
2023-09-26T14:34:12.195+0000 [APP/PROC/WEB/0] STDERR at PostgresService.rollback (/home/vcap/app/node_modules/@cap-js/db-service/lib/common/DatabaseService.js:88:14)
2023-09-26T14:34:12.195+0000 [APP/PROC/WEB/0] STDERR at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-26T14:34:12.195+0000 [APP/PROC/WEB/0] STDERR at async PostgresService.rollback (/home/vcap/app/node_modules/@sap/cds/lib/srv/srv-tx.js:103:66)
2023-09-26T14:34:12.195+0000 [APP/PROC/WEB/0] STDERR at async ODataRequest.emit (/home/vcap/app/node_modules/@sap/cds/lib/req/context.js:52:9)
2023-09-26T14:34:12.195+0000 [APP/PROC/WEB/0] STDERR at async ApplicationService.rollback (/home/vcap/app/node_modules/@sap/cds/lib/srv/srv-tx.js:157:7)
2023-09-26T14:34:12.195+0000 [APP/PROC/WEB/0] STDERR at async /home/vcap/app/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/read.js:503:9
```

|:------------------|---------------------------------------|
| OData version     | v4                                |
| Node.js version   | v18.x.x                               |
| @sap/cds          | 7.x.x                                 |
| @cap-js/postgres | 1.x.x |

**Comment by patricebender** [comment]
@johannes-vogel do you have an idea what might is going wrong here w.r.t. the connection pooling?

**Comment by johannes-vogel** [comment]
I've seen something similar and I think this https://github.com/cap-js/cds-dbs/pull/243 fixes this already.

**Comment by patricebender** [comment]
new version is released, hence closing. Feel free to re-open if the issue persists.
