### ISSUE TITLE
Postgresql - deploy does not check for existing DB schema 

### ISSUE THREAD

**Issue by sedacrivity** [cap-js/cds-dbs#258]
### Description of erroneous behaviour 

> Error / Suggestion

There is no actual check that a (local) defined DB schema exists when trying to deploy.
A 'resourcerequest time out' error is thrown instead.

In the DB window the following error is visible X times

```sh
[102] FATAL:  database "xxx" does not exist
```

Ideally the schema is created automatically ?  Or at least a user friendly warning should be given.

> When deploying to postgresql we get the following errors: 

```sh
cds deploy
/> deployment to localhost:5432 failed

TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/home/.../node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/home/.../node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
Active connections:0
```

### Details about your project

| Node.js                | v18.16.1    |
| @sap/cds               | 7.2.1       |
| @sap/cds-compiler      | 4.2.4       |
| @sap/cds-dk            | 7.2.0       |

**Comment by patricebender** [comment]
@simonoswald could you have a look? If there is no schema present, it would probably better to throw a nice error.
