### ISSUE TITLE
OData Get request leaves Open Transaction

### ISSUE THREAD

**Issue by planctron** [cap-js/cds-dbs#318]
### Description of Error
We use the last recent version of @cap-js/postgres  to access a very simple test model.
There is one table (x_aha_batch) with one record. 
A first GET  via OData endpoint works correctly!
Every following request fails with the db complaining about an "open transaction".
PostgreSQL Log:
```
 LOG:  unexpected EOF on client connection with an open transaction
```
CDS Log:   (First GET is successful!)   Calling the URL again  leads to cds error!
```
[odata] - GET /odata/v4/admin/x_aha_batch 
[odata] - GET /odata/v4/admin/x_aha_batch 
[cds] - TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/home/node/.npm/lib/node_modules/@cap-js/postgres/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/home/node/.npm/lib/node_modules/@cap-js/postgres/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Active connections:1
Error: begin called from:
    at Pool.acquire (/home/node/.npm/lib/node_modules/@cap-js/postgres/node_modules/@cap-js/db-service/lib/common/generic-pool.js:18:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresService.acquire (/home/node/.npm/lib/node_modules/@cap-js/postgres/node_modules/@cap-js/db-service/lib/common/DatabaseService.js:96:12)
    at async PostgresService.begin (/home/node/.npm/lib/node_modules/@cap-js/postgres/node_modules/@cap-js/db-service/lib/common/DatabaseService.js:57:16)
    at async PostgresService._begin (/home/node/.npm/lib/node_modules/@cap-js/postgres/node_modules/@sap/cds/lib/srv/srv-tx.js:205:3)
    at async ApplicationService.<anonymous> (/home/node/app/16aha/node_modules/@sap/cds/libx/_runtime/common/generic/crud.js:73:16)
    at async next (/home/node/app/16aha/node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:17)
    at async ApplicationService.handle (/home/node/app/16aha/node_modules/@sap/cds/lib/srv/srv-dispatch.js:77:10)
    at async _readCollection (/home/node/app/16aha/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/read.js:249:19)
    at async /home/node/app/16aha/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/read.js:480:16 {
  id: '1708262',
  level: 'ERROR',
  timestamp: 1697796379177
}

``` 
Why does a READ request open a transaction?  No other call was made after the   server start  (cds watch ...)

**Comment by patricebender** [comment]
@BobdenOs @johannes-vogel any idea? 

---

@planctron would be nice if you could provide us with a sample repo with steps to reproduce the issue.

**Comment by planctron** [comment]
Thank you. Yes, will provide. I had a few manual steps.
But of course things like the configuration of  db access  must be included.
At first sight, there is nothing, I could have done wrong since a connection, whatever I configure, should not work once and fail a second time.
It was repeatable.

Give me some days, please.
Best regards

**Comment by planctron** [comment]
I try to configure a container.  I could not yet replicate the problem.
Now  I cannot get the postgres-config   to find  the file   .cdsrc.json  in my project root.

I also find this  remark in the   log  of cds watch  --profile pg:

```
WARNING: Package '@sap/cds' was loaded from different installations: [
  '/home/node/app/node_modules/@sap/cds/lib/index.js',
  '/home/node/.npm/lib/node_modules/@cap-js/postgres/node_modules/@sap/cds/lib/index.js'
] Rather ensure a single install only to avoid hard-to-resolve errors.
```

Can this be related?

Over all, I guess, we close this ticket. It may have been a weird  problem.
If it reoccurs,  I would open a new issue.
