### ISSUE TITLE
SQLite: Update can lead to Uncaught RangeError: Invalid time value

### ISSUE THREAD

**Issue by nlaenger** [cap-js/cds-dbs#409]
### Description of erroneous behaviour 

When updating a string field with a text containing a JS timestamp it will result in an ungaught excption.
example
```TS
  LOG._info && LOG.info("This will break:");
  await UPDATE.entity(Belege)
    .with({
      descr: 'Timestamp in JS looks like "2025-04-01T15:00:00Z"',
    })
    .where({ ID: "0f3966ef-142c-4d72-9694-c0f06e898d98" });
```

Will result in:
```sh
[cds] - ❗️Uncaught RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at CQN2SQLite.val (C:\issue-cds-sqlite-text-timestamp\node_modules\@cap-js\db-service\lib\cqn2sql.js:770:49)
    at CQN2SQLite.val (C:\issue-cds-sqlite-text-timestamp\node_modules\@cap-js\sqlite\lib\SQLiteService.js:177:20)
    at C:\issue-cds-sqlite-text-timestamp\node_modules\@cap-js\db-service\lib\cqn2sql.js:553:38
    at _add (C:\issue-cds-sqlite-text-timestamp\node_modules\@cap-js\db-service\lib\cqn2sql.js:558:40)
    at CQN2SQLite.UPDATE (C:\issue-cds-sqlite-text-timestamp\node_modules\@cap-js\db-service\lib\cqn2sql.js:553:15)
    at CQN2SQLite.render (C:\issue-cds-sqlite-text-timestamp\node_modules\@cap-js\db-service\lib\cqn2sql.js:72:15)
    at SQLiteService.cqn2sql (C:\issue-cds-sqlite-text-timestamp\node_modules\@cap-js\db-service\lib\SQLService.js:292:20)
    at SQLiteService.onSIMPLE (C:\issue-cds-sqlite-text-timestamp\node_modules\@cap-js\db-service\lib\SQLService.js:150:34)
    at SQLiteService.onUPDATE (C:\issue-cds-sqlite-text-timestamp\node_modules\@cap-js\db-service\lib\SQLService.js:126:17)
```

it seams the regex [in @cap-js/sqlite/lib/SQLiteService.js](https://github.com/cap-js/cds-dbs/blob/251575b8497e305eea575391a875475a7d083b9a/sqlite/lib/SQLiteService.js#L176) sees a correct date within the string and from there it gets bad.

### Detailed steps to reproduce

> For example (→ replace by appropriate ones for your case):
> 1. git clone https://github.com/nlaenger/issue-cds-sqlite-text-timestamp.git
> 2. npm install
> 3. npm run start

### Details about your project

| Your Project Name | https://github.com/nlaenger/issue-cds-sqlite-text-timestamp |
|:------------------|---------------------------------------|
| @sap/cds          | 7.5.2                               |
@cap-js/sqlite | 1.4.0 |

@fabiantschirschnitz

**Comment by BobdenOs** [comment]
@nlaenger thanks for reporting this issue. It should be fixed by the changes in #410.

The purpose of this check is to allow for more accurate `WHERE` clause behaviors. As `SQLite` does not have `Date` / `Time` types it is not possible to do a binary comparisons. Therefor all `Date` / `Time` values are stored in `Timestamp` format. Which causes a small side effect that when reading a `DateTime` column and using the result inside a `WHERE` clause for it to not match anything. So this check looks for these instances and unifies it with how the value is stored on the database.

```js
const { entity } = cds.entities
const [{ datetime }] = await CQL`SELECT datetime FROM ${entity}`
console.log(datetime) // prints: `YYYY-MM-DDThh:mm:ssZ`
const [{ count }] = await CQL`SELECT count FROM ${entity} WHERE datetime = ${{val: datetime}}`
console.log(count) // prints: n>=1 (without unification always returns 0)
```

For all databases that have `Date` / `Time` types the raw string is send to the database and parsed by the database into their internal binary format and compared accordingly.
