### ISSUE TITLE
[hana] Self-join query throws error inside cap-js/hana

### ISSUE THREAD

**Issue by d-schroeder** [cap-js/cds-dbs#891]
### Description of erroneous behaviour 

Using the latest versions of CAP and @cap-js/hana, I get an error when using a self-join select query, that used to work with cap 7.3.0 and @sap/cds-hana 2.0.0. The query is as follows:

```js
SELECT.from(
  "namespace.itemView a, namespace.itemView b"
)
  .columns("a.itemID as referenceItemID", "b.itemID as matchingItemID").where({...})
```

It seems to me, that the error comes from the class CQN2SQLRenderer in @cap-js/db-service/lib/cqn2sql.js, more specifically the `from` function. This constructs the JOIN-part of the query and always expects an ON-part. Now obviously that would be a problem for self-join or cross-join queries, since they are completely valid without an ON. [Here](https://github.com/cap-js/cds-dbs/blob/d8139fa2ea0cb6bebf966ac5b781b2f8f7c67207/db-service/lib/cqn2sql.js#L367) you can find the exact line that is problematic.
The error should be easily reproducable in any given project by trying to do a self-join of a view or entity.

This is the stacktrace of the error, where you can see the unexpected undefined, which is triggered as a consequence of the from functions design.

[cds] - ❗️Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at CQN2HANA.is_comparator (/Users/user/dev/project/node_modules/@cap-js/hana/lib/HANAService.js:961:33)
    at CQN2HANA.where (/Users/user/dev/project/node_modules/@cap-js/hana/lib/HANAService.js:806:27)
    at CQN2HANA.from (/Users/user/dev/project/node_modules/@cap-js/db-service/lib/cqn2sql.js:367:97)
    at CQN2HANA.SELECT (/Users/user/dev/project/node_modules/@cap-js/db-service/lib/cqn2sql.js:239:45)
    at CQN2HANA.SELECT (/Users/user/dev/project/node_modules/@cap-js/hana/lib/HANAService.js:455:13)
    at CQN2HANA.from (/Users/user/dev/project/node_modules/@cap-js/db-service/lib/cqn2sql.js:365:47)
    at CQN2HANA.SELECT (/Users/user/dev/project/node_modules/@cap-js/db-service/lib/cqn2sql.js:239:45)
    at CQN2HANA.SELECT (/Users/user/dev/project/node_modules/@cap-js/hana/lib/HANAService.js:455:13)
    at CQN2HANA.from (/Users/user/dev/project/node_modules/@cap-js/db-service/lib/cqn2sql.js:365:47)
    at CQN2HANA.SELECT (/Users/user/dev/project/node_modules/@cap-js/db-service/lib/cqn2sql.js:239:45)
    at CQN2HANA.SELECT (/Users/user/dev/project/node_modules/@cap-js/hana/lib/HANAService.js:455:13)
    at CQN2HANA.render (/Users/user/dev/project/node_modules/@cap-js/db-service/lib/cqn2sql.js:89:15)
    at HANAService.cqn2sql (/Users/user/dev/project/node_modules/@cap-js/db-service/lib/SQLService.js:388:20)
    at HANAService.onSELECT (/Users/user/dev/project/node_modules/@cap-js/hana/lib/HANAService.js:137:69)
    at next (/Users/user/dev/project/node_modules/@sap/cds/lib/srv/srv-dispatch.js:69:36)
    at HANAService.onNOTFOUND (/Users/user/dev/project/node_modules/@cap-js/hana/lib/HANAService.js:197:20)
 
### Details about your project

@cap-js/asyncapi: 1.0.2
@cap-js/cds-types: 0.7.0
@cap-js/db-service: 1.14.1
@sap/cds: 8.4.1
@sap/cds-compiler: 5.4.2
@sap/cds-dk: 8.4.1
@sap/cds-dk (global): 8.4.1
@sap/cds-fiori: 1.2.7
@sap/cds-foss: 5.0.0
@sap/cds-mtxs: 2.3.0
@sap/eslint-plugin-cds: 3.1.2
Node.js: v20.8.1

**Comment by d-schroeder** [comment]
@patricebender For us this is a blocker for the upgrade to v8, which we need to get the $top parameter in expand queries. Can you provide any estimation when this should be fixed?

**Comment by d-schroeder** [comment]
Thanks a lot for the quick fix!
