### ISSUE TITLE
`UPSERT` ends up in dump

### ISSUE THREAD

**Issue by patricebender** [cap-js/cds-dbs#94]
```
> UPSERT.into(Books).entries( {ID: 201, texts: [ { locale: 'es', descr: 'Òla'  } ] } ).toSQL()
```

ends up in

```log
Uncaught TypeError: Cannot read properties of undefined (reading 'timestamp')
    at /Users/patricebender/SAPDevelop/cloud-cap-samples/node_modules/@cap-js/db-service/lib/cqn2sql.js:569:46
    at Array.map (<anonymous>)
    at CQN2SQLite.managed (/Users/patricebender/SAPDevelop/cloud-cap-samples/node_modules/@cap-js/db-service/lib/cqn2sql.js:558:45)
    at CQN2SQLite.INSERT_entries (/Users/patricebender/SAPDevelop/cloud-cap-samples/node_modules/@cap-js/db-service/lib/cqn2sql.js:267:30)
    at CQN2SQLite.INSERT (/Users/patricebender/SAPDevelop/cloud-cap-samples/node_modules/@cap-js/db-service/lib/cqn2sql.js:244:14)
    at CQN2SQLite.UPSERT (/Users/patricebender/SAPDevelop/cloud-cap-samples/node_modules/@cap-js/db-service/lib/cqn2sql.js:360:18)
    at CQN2SQLite.render (/Users/patricebender/SAPDevelop/cloud-cap-samples/node_modules/@cap-js/db-service/lib/cqn2sql.js:44:14)
    at SQLiteService.cqn2sql (/Users/patricebender/SAPDevelop/cloud-cap-samples/node_modules/@cap-js/db-service/lib/SQLService.js:185:51)
    at Query.toSQL (/Users/patricebender/SAPDevelop/cloud-cap-samples/node_modules/@cap-js/db-service/lib/SQLService.js:279:46)
```

**Comment by patricebender** [comment]
fixed in the meanwhile:

```
> { Books, Authors } = cds.entities
(ns) => !ns ? children : this.childrenOf (ns,filter)
> UPSERT.into(Books).entries( {ID: 201, texts: [ { locale: 'es', descr: 'Òla'  } ] } ).toSQL()
{
  sql: `INSERT INTO sap_capire_bookshop_Books (createdAt,createdBy,modifiedAt,modifiedBy,ID,title,descr,author_ID,genre_ID,stock,price,currency_code,image,authorAge) SELECT ISO(value->>'$."createdAt"'),value->>'$."createdBy"',coalesce(ISO(value->>'$."modifiedAt"'), session_context('$now')),coalesce(value->>'$."modifiedBy"', session_context('$user.id')),value->>'$."ID"',value->>'$."title"',value->>'$."descr"',value->>'$."author_ID"',value->>'$."genre_ID"',value->>'$."stock"',value->>'$."price"',value->>'$."currency_code"',value->>'$."image"',value->>'$."authorAge"' FROM json_each(?) WHERE true ON CONFLICT(ID) DO UPDATE SET texts = excluded.texts`,
  values: []
}
```
